server:
  port: 8880
  servlet:
    context-path: /

spring:
  application:
    name: ohmyraid-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/omr
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    generate-ddl: true
    show-sql: true
  messages:
    cache-duration: -1
    basename: classpath:/i18n/messages
    encoding: UTF-8

logging:
  level:
    root: INFO
    com.ohmyraid: INFO
  file:
    path: logs

# Swagger 설정
#springfox:
#  documentation:
#    swagger:
#      v2.path: /swagger/swagger.json
#      use-service: OMR
#      ui-enabled: true
#      group-name: OMR-API
#      description: OhMyRaid-API
#      post-paths: /*.*|/s/*.*

feign:
  client:
    config:
      RAD:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000