### Authorization 토큰값은 계속 변경해줘야함!!
GET http://localhost:8880/character/raid-encounter
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJvaG15cmFpZCIsImlhdCI6MTYzMjQ1ODI3MywiTG9naW5JZCI6ImdoNTY3MEBuYXZlci5jb20iLCJVc2VyTmFtZSI6Iuq3vOywqOuLiCIsImV4cCI6MTYzMjQ5NDI3M30.s99Y-bofgU3JEuU-aFITdidO4eQVhptMSwO8cqYyODyDHfwsyZfwIUc54J7-QprrmqXdw9-Xq8BXS-gRrx5NXA
