### Authorization 토큰값은 계속 변경해줘야함!!
GET http://localhost:8880/character/raid-encounter
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJvaG15cmFpZCIsImlhdCI6MTYzMTI1NTMzOSwiTG9naW5JZCI6ImdoNTY3MEBuYXZlci5jb20iLCJVc2VyTmFtZSI6Iuq3vOywqOuLiCIsImV4cCI6MTYzMTI5MTMzOX0.PcXhqcdXJQ_QTfwFZ9Uiw-OcjnzB6TDp08tkOj0rML-EIfsZJSrhoVAhZoAnrP57K96sb52nGE-8AV4USjukVQ
