### Test
GET http://localhost:8880/account/test

###

### SignUp Test
POST http://localhost:8880/account/signup
Content-Type: application/json

{
"email" : "donghaynzxc@gmail.com",
"password" : "qwe123",
  "nickname" : "박동"
}

###
POST http://localhost:8880/account/signup
Content-Type: application/json

< ./dummy.json