# Docker-compose to set omr dev environment

version: '2'

services:
  database:
    image: mysql
    container_name: omr-mysql
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${OMR_MYSQL_PASSWORD}
      TZ : Asia/Seoul #docker compose yml 자체에 TimeZone을 박아놓는것도 방법이다.
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    volumes:
      - /Users/autocat/dev/Personal/docker-mysql

  redis:
    image: redis
    container_name: omr-redis
    ports:
      - "46379:6379"

  #Grafana


  #Prometheus
