# curl -u {client_id}:{client_secret} -d grant_type=client_credentials https://oauth.battle.net/token
POST https://oauth.battle.net/token
Authorization: Basic cd5f2cc20f0e4be08e31ae9938e56b2d 1penStTopokgRhM4fRtGwez2JUwyc7K2
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials

> {% client.global.set("battlenetAccessToken", response.body.access_token ); %}

###
# KRNdYJGem6irHHexP4lcEnhZm05qo0jcws


###

GET https://kr.api.blizzard.com/profile/wow/character/azshara/%EB%88%88%EB%B6%88%20?namespace=profile-kr&locale=ko_KR&
    access_token={{battlenetAccessToken}}

###

GET https://kr.api.blizzard.com/profile/wow/character/azshara/%EB%B0%95%EB%8F%99%ED%98%84/encounters/raids?
    namespace=profile-kr&locale=ko_KR&access_token={{battlenetAccessToken}}

###

GET https://kr.api.blizzard.com/profile/wow/character/azshara/%EC%98%A4%ED%86%A0%EC%BA%A3?namespace=profile-kr&
    access_token=KRm9DAIW5ebM6MTg8x134oIP8t6BxG4h8J&locale=ko_KR


###
#Raider MythicPlusScoreBySeason:current
GET https://raider.io/api/v1/characters/profile?region=kr&realm=azshara&name=눈불&
    fields=mythic_plus_scores_by_season%3Acurrent
Content-Type: application/json

###
GET https://www.warcraftlogs.com/oauth/token
Authorization: Basic cd5f2cc20f0e4be08e31ae9938e56b2d 1penStTopokgRhM4fRtGwez2JUwyc7K2

###
GET http://localhost:8880/characters/1/raids?characterId=19&difficulty=4&expansionId=395